name: Deploy to Server TENCENT LIGHTHOUSE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.TCLH_SSH_KEY }}

      - name: Prepare SSH
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan ${{ secrets.TCLH_SERVER_IP }} >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Sync www directory to Server with Incremental Update
        run: |
          # 使用 rsync 的增量同步特性
          # --partial: 断点续传
          # --compress: 传输时压缩
          # --progress: 显示进度
          # -u: 只同步新文件或更新的文件
          # --delete-after: 在传输完成后删除目标目录中多余的文件
          rsync -avuz \
            --partial \
            --compress \
            --progress \
            -e "ssh -o StrictHostKeyChecking=no" \
            --delete-after \
            --chmod=Du=rwx,Dgo=rx,Fu=rw,Fgo=r \
            www/ \
            ${{ secrets.TCLH_SERVER_USER }}@${{ secrets.TCLH_SERVER_IP }}:/opt/docker/nginx/html/

      - name: Verify and Set Ownership
        run: |
          # 使用 sudo 确保正确设置权限
          ssh -o StrictHostKeyChecking=no \
              ${{ secrets.TCLH_SERVER_USER }}@${{ secrets.TCLH_SERVER_IP }} \
              "
              # 递归设置目录权限
              sudo chown -R root:root /opt/docker/nginx/html
              sudo chmod -R 755 /opt/docker/nginx/html
              
              # 显示目录内容和权限
              ls -la /opt/docker/nginx/html
              
              # 检查文件数量
              echo '文件数量:'
              find /opt/docker/nginx/html -type f | wc -l
              "

      - name: Reload Nginx Docker Container
        run: |
          ssh -o StrictHostKeyChecking=no \
              ${{ secrets.TCLH_SERVER_USER }}@${{ secrets.TCLH_SERVER_IP }} \
              "
              cd /opt/docker/nginx
              docker compose down
              docker compose up -d
              "
# test mark