name: Deploy to Server TENCENT LIGHTHOUSE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.TCLH_SSH_KEY }}

      - name: Prepare SSH
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan ${{ secrets.TCLH_SERVER_IP }} >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Verify SSH Connection
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.TCLH_SERVER_USER }}@${{ secrets.TCLH_SERVER_IP }} \
            "echo 'SSH connection successful'"

      - name: Verify Sudo Privileges
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.TCLH_SERVER_USER }}@${{ secrets.TCLH_SERVER_IP }} \
            "sudo -v || (echo 'Error: User does not have sudo privileges'; exit 1)"

      - name: Create Target Directory (if not exists)
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.TCLH_SERVER_USER }}@${{ secrets.TCLH_SERVER_IP }} \
            "sudo mkdir -p ${{ secrets.TCLH_SERVER_PATH }} && sudo chown -R ${{ secrets.TCLH_SERVER_USER }} ${{ secrets.TCLH_SERVER_PATH }}"

      - name: Sync www directory to Server
        run: |
          rsync -avz --progress --delete \
            -e "ssh -o StrictHostKeyChecking=no" \
            www/ \
            ${{ secrets.TCLH_SERVER_USER }}@${{ secrets.TCLH_SERVER_IP }}:${{ secrets.TCLH_SERVER_PATH }} \
            --rsync-path="sudo rsync"

      - name: Verify Deployment
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.TCLH_SERVER_USER }}@${{ secrets.TCLH_SERVER_IP }} \
            "ls -la ${{ secrets.TCLH_SERVER_PATH }} | head -n 10"