name: Deploy to Server TENCENT LIGHTHOUSE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.TCLH_SSH_KEY }}

      - name: Prepare SSH
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan ${{ secrets.TCLH_SERVER_IP }} >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Verify SSH Connection
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.TCLH_SERVER_USER }}@${{ secrets.TCLH_SERVER_IP }} \
            "echo 'SSH connection successful'"

      - name: Check Target Directory Permissions
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.TCLH_SERVER_USER }}@${{ secrets.TCLH_SERVER_IP }} \
            "mkdir -p ${{ secrets.TCLH_SERVER_PATH }} && \
             touch ${{ secrets.TCLH_SERVER_PATH }}/permission_test && \
             rm ${{ secrets.TCLH_SERVER_PATH }}/permission_test && \
             echo 'Directory has write permissions'"

      - name: Sync www directory to Server
        run: |
          rsync -avz --progress --delete --no-perms --no-owner \
            -e "ssh -o StrictHostKeyChecking=no" \
            www/ \
            ${{ secrets.TCLH_SERVER_USER }}@${{ secrets.TCLH_SERVER_IP }}:${{ secrets.TCLH_SERVER_PATH }}

      - name: Verify Deployment
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.TCLH_SERVER_USER }}@${{ secrets.TCLH_SERVER_IP }} \
            "ls -la ${{ secrets.TCLH_SERVER_PATH }} | head -n 10"