name: Deploy to Server TENCENT LIGHTHOUSE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.TCLH_SSH_KEY }}

      - name: Prepare SSH
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan ${{ secrets.TCLH_SERVER_IP }} >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Prepare Target Directory
        run: |
          ssh -o StrictHostKeyChecking=no \
              ${{ secrets.TCLH_SERVER_USER }}@${{ secrets.TCLH_SERVER_IP }} \
              "
              # 确保目录存在
              sudo mkdir -p /opt/docker/nginx/html
              
              # 临时授予部署用户写权限
              sudo chown -R ${{ secrets.TCLH_SERVER_USER }}:${{ secrets.TCLH_SERVER_USER }} /opt/docker/nginx/html
              sudo chmod -R 775 /opt/docker/nginx/html
              "
      
      - name: Sync www directory to Server with Incremental Update
        run: |
          rsync -avuz \
            --partial \
            --compress \
            --progress \
            -e "ssh -o StrictHostKeyChecking=no" \
            --delete-after \
            --chmod=Du=rwx,Dgo=rx,Fu=rw,Fgo=r \
            www/ \
            ${{ secrets.TCLH_SERVER_USER }}@${{ secrets.TCLH_SERVER_IP }}:/opt/docker/nginx/html/
      
      - name: Restore Ownership and Permissions
        run: |
          ssh -o StrictHostKeyChecking=no \
              ${{ secrets.TCLH_SERVER_USER }}@${{ secrets.TCLH_SERVER_IP }} \
              "
              # 恢复root所有权
              sudo chown -R root:root /opt/docker/nginx/html
              
              # 设置安全权限
              sudo find /opt/docker/nginx/html -type d -exec chmod 755 {} \;
              sudo find /opt/docker/nginx/html -type f -exec chmod 644 {} \;
              
              # 验证权限
              ls -ld /opt/docker/nginx/html
              ls --la /opt/docker/nginx/html | head
              "

      - name: Reload Nginx Docker Container
        run: |
          ssh -o StrictHostKeyChecking=no \
              ${{ secrets.TCLH_SERVER_USER }}@${{ secrets.TCLH_SERVER_IP }} \
              "
              cd /opt/docker/nginx
              docker compose down
              docker compose up -d
              "
# test mark